//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WotPersonalDataCollector.WebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WotPersonalDataCollector.WebApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not cancel operation that was not started or is finished!.
        /// </summary>
        internal static string CancelingCancelledOperationMessage {
            get {
                return ResourceManager.GetString("CancelingCancelledOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling validation..
        /// </summary>
        internal static string CancelingValidation {
            get {
                return ResourceManager.GetString("CancelingValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancellation has already started..
        /// </summary>
        internal static string CancellationOperationHasAlreadyStaredMessage {
            get {
                return ResourceManager.GetString("CancellationOperationHasAlreadyStaredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation token was disposed, that means validation operation is finished..
        /// </summary>
        internal static string CancellationTokenDisposedMessage {
            get {
                return ResourceManager.GetString("CancellationTokenDisposedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} delete process started.
        /// </summary>
        internal static string DataDeleteProcessStarted {
            get {
                return ResourceManager.GetString("DataDeleteProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Operation has already started, can&apos;t start another one. Please wait..
        /// </summary>
        internal static string ValidationOperationIsAlreadyStartedMessage {
            get {
                return ResourceManager.GetString("ValidationOperationIsAlreadyStartedMessage", resourceCulture);
            }
        }
    }
}
